function(gperftools_add_target target_name)
  if(inc)
    target_include_directories(${target_name} PUBLIC ${inc})
  endif()
  if(libs)
    target_link_libraries(${target_name} PUBLIC ${libs})
  endif()
  if(defs)
    target_compile_definitions(${target_name} PUBLIC ${defs})
  endif()
  if(options)
    target_compile_options(${target_name} PUBLIC ${options})
  endif()
endfunction()
